orderservice/ordering/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import *


'''urlpatterns = patterns('ordering.views',

    (r'^$', 'index'),
    (r'^new/$', 'neworder'),
    (r'^details/$', 'orderdetails'),
    (r'^(?P<email>[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', 'listorders'),
    
                       
                       
)
'''

orderservice/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from ordering.views import StatusFeed

__author__ = "David V. Hill"

admin.autodiscover()

urlpatterns = patterns('',
    (r'^rpc$', 'ordering.rpc.rpc_handler'),
    (r'^new','ordering.views.neworder'),
    (r'^status/$', 'ordering.views.listorders'),
    (r'^status/([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$', 'ordering.views.listorders'),
    #(r'^status/(?P<email>[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/(?P<output_format>[A-Za-z]{3})', 'ordering.views.listorders'),
    (r'^status/(?P<email>[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/rss/$', StatusFeed()),
       
    (r'^status/(?P<orderid>[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}-[0-9]{6,8}-[0-9]{3,6})/$', 'ordering.views.orderdetails'),
    (r'^status/(?P<orderid>[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}-[0-9]{13})/$', 'ordering.views.orderdetails'),

    (r'^admin/', include(admin.site.urls)),
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^$', 'ordering.views.neworder'),
    (r'^index', 'ordering.views.index'),                         

)

orderservice/ordering/models.py
from django.db import models
from django.contrib import admin

__author__ = "David V. Hill"

    
class Order(models.Model):

    def __unicode__(self):
        return self.orderid

    DATASETS = (
        ('sr_ondemand', 'Surface Reflectance TM/ETM'),
        ('sr_gls2010', 'Surface Reflectance GLS 2010'),
        ('sr_gls2005', 'Surface Reflectance GLS 2005'),
        ('sr_gls2000', 'Surface Reflectance GLS 2000')
    )
    
    STATUS = (
        ('ordered', 'Ordered'),
        ('partial', 'Partially Filled'),
        ('complete', 'Complete')
        
    )

    ORDER_SOURCE = (
        ('espa', 'ESPA'),
        ('ee', 'EE')
    )
    
    #orderid should be in the format email_MMDDYY_HHMMSS
    orderid = models.CharField(max_length=255, unique=True, db_index=True)
    email = models.EmailField(db_index=True)
    #scenes = models.ManyToManyField(Scene, through = 'SceneOrder')
    #display scene count ordered, scene count completed in UI
    chain = models.CharField(max_length=50,choices=DATASETS,db_index=True)
    order_date = models.DateTimeField('date ordered', blank=True, db_index=True)
    completion_date = models.DateTimeField('date completed', blank=True, null=True, db_index=True)
    status = models.CharField(max_length=20, choices=STATUS,db_index=True)
    note = models.CharField(max_length=2048, blank=True, null=True)
    #json for all product options
    product_options = models.TextField(blank=False,null=False)

    order_source = models.CharField(max_length=10, choices=ORDER_SOURCE,db_index=True)
    ee_order_id = models.CharField(max_length=13, blank=True)

class Scene(models.Model):

    def __unicode__(self):
        display = self.name
        display = display + ' (' + self.status + ')'
        return ('%s') % (display)

    STATUS = (
        ('submitted', 'Submitted'),
        ('onorder', 'On Order'),
        ('oncache', 'On Cache'),
        ('queued', 'Queued'),
        ('staging', 'Staging'),
        ('processing', 'Processing'),
        ('distributing', 'Distributing'),
        ('complete', 'Complete'),
        ('purged', 'Purged'),
        ('unavailable','Unavailable'),
        ('error', 'Error')
    )
    
    #scene file name, with no suffix
    name = models.CharField(max_length=256,db_index=True)
    
    #scene system note, used to add message to users
    note = models.CharField(max_length=2048, blank=True, null=True)

    order = models.ForeignKey(Order)
    
    ###################################################################################
    #  Scene status flags.  The general status of the scene can be determined by the
    #  following flags.  If any path is populated then this means that the path
    #  exists and the file is present at that location
    ###################################################################################
    
    #full path including filename where this scene has been distributed to 
    #minus the host and port. signifies that this scene is distributed
    product_distro_location = models.CharField(max_length=1024, blank=True)
    #full path to where this scene can be downloaded from on the distribution node
    product_dload_url = models.CharField(max_length=1024, blank=True)
    cksum_distro_location = models.CharField(max_length=1024,blank=True)
    cksum_download_url = models.CharField(max_length=1024, blank=True)

    ###################################################################################
    # This will only be populated if the scene had to be placed on order through
    # EE to satisfy the request.
    ###################################################################################
    tram_order_id = models.CharField(max_length=13, blank=True, null=True)
     
    ###################################################################################
    # Flags for order origination.  These will only be populated if the scene request
    # came from EE.
    ###################################################################################
    
    ee_unit_id = models.IntegerField(max_length=11, blank=True, null=True)
    
    ###################################################################################
    # General status flags for this scene
    ###################################################################################
    #Status.... one of Submitted, Ready For Processing, Processing,
    #Processing Complete, Distributed, or Purged
    status = models.CharField(max_length=30, choices=STATUS,db_index=True)

    #Where is this scene being processed at?  (which machine)
    processing_location = models.CharField(max_length=256, blank=True)

    #Time this scene was finished processing
    completion_date = models.DateTimeField('date completed', blank=True, null=True, db_index=True)

    #Final contents of log file... should be put added when scene is marked
    #complete.
    log_file_contents = models.TextField('log_file', blank=True, null=True)
    
               
    
#Simple class to provide centralized configuration for the system
class Configuration(models.Model):
    key = models.CharField(max_length=255, unique=True)
    value = models.CharField(max_length=2048)

    def __unicode__(self):
        return ('%s : %s') % (self.key,self.value)

    def getValue(self, key):
        #print ("Getting config value for key:%s" % key)
        c = Configuration.objects.filter(key=key)
        #print ("returned value for config key is:%s" % c)
        if len(c) > 0:
            return str(c[0].value)
        else:
            return ''



        

orderservice/ordering/views.py
########################################################################################################################
# Views.py
# Purpose: Handles all the interaction with espa web pages
# Original Author: David V. Hill
########################################################################################################################


from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.syndication.views import Feed
from django.contrib.syndication.views import FeedDoesNotExist
from django.shortcuts import get_object_or_404,get_list_or_404
from django.utils.feedgenerator import Rss201rev2Feed
from django.template import Context, loader, RequestContext
from django import forms
from django.core.files.uploadedfile import SimpleUploadedFile
from django.contrib.auth.models import User
from django.contrib.auth import logout
from ordering.models import Scene,Order,Configuration
import core, lta, json
import view_validator as vv
from datetime import datetime


########################################################################################################################
# get_option_style()
# Utility method to determine what options to display based on the user thats logged in
########################################################################################################################
def get_option_style(request):
    if hasattr(request, 'user'):
        user = request.user
        return "display:none" if (user.username != 'espa_admin' and user.username != 'espa_internal') else ""

########################################################################################################################
#default landing page for the ordering application
#@login_required(login_url='/login/')
########################################################################################################################
def index(request):
      
    t = loader.get_template('index.html')
    c = Context({
        'my_message': 'LSDS Science R&D Processing',
    })
            
    return HttpResponse(t.render(c))
                       
########################################################################################################################
#Request handler for /neworder.  Handles getting new orders into the system
########################################################################################################################
@login_required(login_url='/login/')
def neworder(request):
    
    ####################################################################################################################
    #Includes the system message in the request context if one is defined
    ####################################################################################################################
    def include_system_message(request_context):
        msg = Configuration().getValue('system_message')
        if len(msg) > 0 and msg != '' and msg != 'nothing':
            c['system_message'] = msg
    
    
        
    ####################################################################################################################
    #request handling
    ####################################################################################################################
    if request.method == 'GET':
        c = RequestContext(request,{'user':request.user,
                                    'optionstyle':get_option_style(request)}
                           )
        #t = loader.get_template('neworder.html')
        t = loader.get_template('rework.html')
        include_system_message(c)
        return HttpResponse(t.render(c))
        
    elif request.method == 'POST':
        #request must be a POST and must also be encoded as multipart/form-data 
        #in order for the files to be uploaded
        
        context, errors, scene_errors = vv.validate_input_params(request)
        prod_option_context, prod_option_errors = vv.validate_product_options(request)
        
        if len(prod_option_errors) > 0:
            errors['product_options'] = prod_option_errors
        if len(scene_errors) > 0:
            errors['scenes'] = scene_errors
        
        print prod_option_context
        print "ERRORS"
        print errors
        
        if len(errors) > 0:
            print "Errors Detected..."
            c = RequestContext(request, {'errors':errors,
                                         'user':request.user,
                                         'optionstyle':get_option_style(request)}
                               )    
            t = loader.get_template('rework.html')
            include_system_message(c)
            return HttpResponse(t.render(c))
        else:
            print "No errors detected"
            
            option_string = json.dumps(prod_option_context)
            
            print "Option String"
            print option_string
            print "Saving new order"
            order = core.enter_new_order(context['email'], 'espa', context['scenelist'], option_string, note = context['order_description'])
            print "Sending email"
            core.sendInitialEmail(order)
            print "Redirecting to status page"
            
            return HttpResponseRedirect('/status/%s' % request.POST['email'])


########################################################################################################################
#handles displaying all orders for a given user
########################################################################################################################
#@login_required(login_url='/login/')
@csrf_exempt
def listorders(request, email=None, output_format=None):

    #no email provided, ask user for an email address
    if email is None or not core.validate_email(email):
        form = ListOrdersForm()
        c = RequestContext(request,{'form': form})
        t = loader.get_template('listorders.html')
        return HttpResponse(t.render(c))

    #if we got here it's all good, display the orders
    orders = core.list_all_orders(email)
    t = loader.get_template('listorders_results.html')
    mimetype = 'text/html'   
    c = RequestContext(request)
    c['email'] = email
    c['orders'] = orders
    return HttpResponse(t.render(c), mimetype=mimetype)


########################################################################################################################
# Request handler to get the full listing of all the scenes & statuses for an order
########################################################################################################################
@csrf_exempt
def orderdetails(request, orderid, output_format=None):
    '''displays scenes for an order'''           

    t = loader.get_template('orderdetails.html')
    mimetype = 'text/html'   
    c = RequestContext(request)

    order,scenes = core.get_order_details(orderid)
    c['order'] = order
    c['scenes'] = scenes

    return HttpResponse(t.render(c), mimetype=mimetype)
        
        

########################################################################################################################
# Form Objects
########################################################################################################################
class ListOrdersForm(forms.Form):
    email = forms.EmailField()

class OrderForm(forms.Form):
    email = forms.EmailField()
    #add fields here for scene uploads
    files = forms.FileField()
    #dataset = forms.ChoiceField(choices=Order.DATASETS,required=True)
    note = forms.CharField(widget=forms.Textarea(attrs={'cols':'80'}))
    
    include_sourcefile = forms.BooleanField(initial=False)
    include_source_metadata = forms.BooleanField(initial=True)
    include_sr_toa = forms.BooleanField(initial=True)
    include_sr_thermal = forms.BooleanField(initial=False)
    include_sr = forms.BooleanField(initial=True)
    include_sr_browse = forms.BooleanField(initial=False)
    include_sr_ndvi = forms.BooleanField(initial=False)
    include_sr_ndmi = forms.BooleanField(initial=False)
    include_sr_nbr = forms.BooleanField(initial=False)
    include_sr_nbr2 = forms.BooleanField(initial=False)
    include_sr_savi = forms.BooleanField(initial=False)
    include_sr_evi = forms.BooleanField(initial=False)
    include_solr_index = forms.BooleanField(initial=False)
    include_cfmask = forms.BooleanField(initial=False)
        
########################################################################################################################

########################################################################################################################
class StatusFeed(Feed):
    feed_type = Rss201rev2Feed
    title = "ESPA Status Feed"
    link = ""
    
    def get_object(self, request, email):
        return get_list_or_404(Order, email=email)

    def link(self, obj):
        return "/status/%s/rss/" % obj[0].email
    
    def description(self, obj):
        #return "status:" % obj.status
        return "ESPA scene status for:%s" % obj[0].email
    
    def item_title(self, item):
        return item.name
    
    def item_link(self, item):
        return item.product_dload_url
    
    def item_description(self, item):
        orderid = item.order.orderid
        orderdate = item.order.order_date
        return "scene_status:%s,orderid:%s,orderdate:%s" % (item.status, orderid, orderdate)
           
    def items(self, obj):
        email = obj[0].email
        
        return Scene.objects.filter(status='complete',order__email=email).order_by('-order__order_date')

        

orderservice/ordering/templates/bulk_ordering_nav.html
 <div id="nav">
                <span class="navitem"><a href="/index">Home</a></span>
		<span class="navitem">|</span>
                <span class="navitem"><a href="http://landsat.usgs.gov/CDR_ECV.php">Product Information</a></span>
		<span class="navitem">|</span>
		<span class="navitem"><a href="/new">New Order</a></span>   
		<span class="navitem">|</span>
		<span class="navitem"><a href="/status">Show Orders</a></span>		
 </div>		

orderservice/ordering/templates/listorders.html
{% extends "base.html" %}

{% block title %} Bulk Order Status {% endblock %}
{% block header %}Bulk Order Status {% endblock %}
{% block style %}

	span.error {
		color:red;
	}

{% endblock %}

{% block nav %}{% include "bulk_ordering_nav.html" %}{% endblock %}

{% block content %}
<!--<form action="/status/" method="post"> {% csrf_token %}-->
<div id="wrapper">
    
    <h4>Show Orders</h4>
    <p>
            Please enter the email address used to submit the order.
   </p>
        
    {% if errors.email %}
    <span class="error">{{errors.email}}</span><br/>
    {% endif %}
    <p>
    <label for="id_email">Email address:</label>
    {{form.email}}
    </p>
        
    <p>
	<!--<input type="submit" value="Submit"' />-->
	<input type="button" value="Submit" onclick='switchUrl();' />
    </p>

</div>

<!--</form>-->

<div class="footer"></div>

<div class="spacer"></div>


<script type='text/javascript'>
 function switchUrl() {
    var email_addr = document.getElementById('id_email');
    window.location = window.location + email_addr.value;
    return false;
 }
</script>
{% endblock %}

orderservice/ordering/templates/listorders_results.html
{% extends "base.html" %}

{% block title %} Show all orders {% endblock %}

{% block header %}
{% if email %}
    Showing all orders for: {{ email }}
{% else %}
    Show all orders
{% endif %}
{% endblock %}

{% block content %}
<form action="/list/" method="post">
{% csrf_token %}
<div id="wrapper">

{% if orders %}
<h4>
<a href="/status/{{email}}/rss/"><img border="0" alt="RSS Status Feed" title="Completed Scene RSS Feed" src="http://landsat.usgs.gov/espa/images/feed-icon-28x28.png"></img></a>
&nbsp;&nbsp;Showing all orders for {{email}}
</h4>

{% for order in orders %}
    <div>
    <a href='/status/{{order.orderid}}'>{{order.orderid}}</a><span style="margin-left:10px">{{order.get_status_display}}</span>
    </div>
    <div style="margin-bottom:10px;margin-top:5px;">
	{{order.note}}
    </div>
    
{% endfor %}
{% else %}
<h4>No orders found for {{email}}</h4>
{% endif %}
</div>
<div class="footer"></div>

<div class="spacer"></div>
{% endblock %}

orderservice/ordering/templates/login.html
{% extends "base.html" %}
{% load url from future %}


{% block title %}Ordering Interface{% endblock %}
{% block header %} ESPA Ordering Interface {% endblock %}

{% block content %}

<div id="wrapper">
	
	<h4>Please log in to continue</h4>


	<form method="post" action="{% url 'django.contrib.auth.views.login' %}" method="post">
		{% csrf_token %}
		
		<table>
		<tr>
		<td>
		{{ form.username.label_tag }}
		</td>
		<td style="padding-left:10px;">
		{{ form.username }}
		</td>
		</tr>
		<tr><td>&nbsp;</td><td>&nbsp;</td></tr>
		<tr>
		<td>
		{{ form.password.label_tag }}
		</td>
		<td style="padding-left:10px;">
		{{ form.password }}
		</td>
		</tr>
		<tr><td>&nbsp;</td><td>&nbsp;</td></tr>
		<tr>
		<td>
		<input type="submit" value="Log In" />
		<input type="hidden" name="next" value="{{next}}" />
		</td>
		</tr>
		</table>

	</form>

	<h5 style="padding-top:55px">To obtain a username/password complete the <a href="http://landsat.usgs.gov/contactus.php">Contact Form</a>, selecting the Surface Reflectance Data/LAI Request topic.</h5>

</div>

<div class="footer"></div>

<div class="spacer"></div>

{% endblock %}

orderservice/ordering/templates/neworder.html
{% extends "base.html" %}

{% block title %} New Bulk Order {% endblock %}
{% block header %} New Bulk Order {% endblock %}
{% block style %}

	div#wrapper {
		margin:auto;
		width:800px;
	}

        div#errorbox{
	     margin:0 auto;
	     border:2px solid red;
	     width:100%;
	     color:red;
	   
	}
	
	div#errorbox table {
	    width:700px;
	}
	
	div#errorbox td{
	    font-size:16px;
	    color:red;
	    padding:5px 25px;
	    
	}

		
{% endblock %}

{% block nav %}{% include "bulk_ordering_nav.html" %}{% endblock %}


{% block content %}
<form action="/new/" method="post" enctype="multipart/form-data"> {% csrf_token %}


<div id="wrapper">
    
    {% if system_message %}
    <div style="vertical-align:middle;border:4px solid red; margin-top:20px;padding:15px 10px 15px 10px;font-color:red;font-size:18px;">{{system_message}}</div>
    {% endif %}
   
    <h4>Submitting an order</h4>
    <p>
            Submitting a new order is as simple as entering your email address 
            along with a file containing your scene list and pressing the submit button
            at the bottom of the page. For more information on creating a scene list file, 
            please refer to the 
            <a href="http://glovis.usgs.gov/ImgViewerHelp.shtml#SaveLoadSceneLists" target="blank">user guide instructions</a>
            on saving and loading scene lists for the 
            <a href="http://glovis.usgs.gov/" target="blank">USGS Global Visualization Viewer</a>.
   </p>
        
    {% if errors.email or errors.file or errors.scenes %}
	<div id="errorbox">
	    <table><tr><td><strong>Errors were found in your request.&nbsp;&nbsp;Please correct them and retry your order.</strong></td></tr>
    {% endif %}
    {% if errors.email %}
	<tr><td>{{errors.email}}</td></tr>
    {% endif %}
    {% if errors.file %}
        <tr><td>{{errors.file}}</td></tr>
    {% endif %}
    {% if errors.scenes %}
    {% for err_scene in errors.scenes %}
        <tr><td>{{err_scene}}</td></tr>
    {% endfor %}
    {% endif %}
    {% if errors.email or errors.file or errors.scenes %}
	    </table>
	</div>
    {% endif %}
    
    <br/>
    <div style="text-align:center;margin:0 auto;width:800px;padding:4px;font-size:20px;">

      <!--  <div style="float:left;width:250px;overflow:hidden;font-size:14px; margin-left:20px;margin-right:20px;">
        <div style="text-align:center;line-height: 30px;font-size: 14px;color:white;background:#577196;overflow:hidden;font-weight:bold;">
         <p>Spectral Indices</p>
        </div>
 
        <div style="border:1px solid  #d0d0d0;
           -moz-border-radius-bottomright: 5px;
           -moz-border-radius-bottomleft: 5px;
           -webkit-border-radius-bottomleft: 5px;
           -webkit-border-radius-bottomright: 5px;
           border-bottom-left-radius:5px;
           border-bottom-right-radius:5px;
           line-height:25px;
">
         
         <table style="width:100%;margin:auto;">
         <tr>
         <td style="padding-left:5px;text-align:left;">Surface Reflectance NDVI</td>
         <td style="padding-right:5px;"><input style="text-align:right" type="checkbox" /></td>
         </tr>
         <tr style="background:#e1e1e1;">
         <td style="padding-left:5px;text-align:left">Surface Reflectance NDMI</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         <tr>
         <td style="padding-left:5px;text-align:left">Surface Reflectance NBR</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         <tr style="background:#e1e1e1;">
         <td style="padding-left:5px;text-align:left">Surface Reflectance NBR2</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         <tr>
         <td style="padding-left:5px;text-align:left">Surface Reflectance EVI</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         <tr style="background:#e1e1e1;">
         <td style="padding-left:5px;text-align:left">Surface Reflectance SAVI</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         </table>
        </div>
        </div>


 <div style="float:left;width:250px;overflow:hidden;font-size:14px;">
        <div style="text-align:center;line-height: 30px;font-size: 14px;color:white;background:#577196;overflow:hidden;font-weight:bold;">
         <p>Reflectance Products</p>
        </div>
 
        <div style="border:1px solid  #d0d0d0;
           -moz-border-radius-bottomright: 5px;
           -moz-border-radius-bottomleft: 5px;
           -webkit-border-radius-bottomleft: 5px;
           -webkit-border-radius-bottomright: 5px;
           border-bottom-left-radius:5px;
           border-bottom-right-radius:5px;
           line-height:25px;
">
         
         <table style="width:100%;margin:auto;">
         <tr>
         <td style="padding-left:5px;text-align:left">Top of Atmosphere Reflectance</td>
         <td style="padding-right:5px;" ><input style="text-align:right" type="checkbox" /></td>
         </tr>
         <tr style="background:#e1e1e1;">
         <td style="padding-left:5px;text-align:left">Band 6 Brightness Temperature</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         <tr>
         <td style="padding-left:5px;text-align:left">Surface Reflectance</td>
         <td style="padding-right:5px;"><input type="checkbox" /></td>
         </tr>
         </table>
        </div>
        </div>
-->

	<table style="text-align:left">
	    <tr>
		<td colspan=1><h5>Enter your email address:</h5></td>
	        <td colspan=3><input size=40 type="text" name="email" id="id_email" /></td>
	    </tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
	    <tr>
		<td colspan=1><h5>Choose Scene List</h5></td>
	        <td colspan=3><input type=file name="file" size="40"/></td>
	    </tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
          
	    <tr><td colspan=4><h5>Select Product Contents</h5></td></td>
        
         
	    <tr><td colspan=2>Source Products</td><td colspan=2>{{form.include_sourcefile}}</td></tr>
	    <tr><td colspan=2>Source Metadata</td><td colspan=2>{{form.include_source_metadata}}</td></tr>
         

	    <tr><td colspan=2>Top of Atmosphere Reflectance</td><td colspan=2>{{form.include_sr_toa}}</td></tr>
	    <tr><td colspan=2>Band 6 Brightness Temperature</td><td colspan=2>{{form.include_sr_thermal}}</td></tr>
	    <tr><td colspan=2>Surface Reflectance</td><td colspan=2>{{form.include_sr}}</td></tr>
	    <tr><td colspan=2>Surface Reflectance Browse</td><td colspan=2>{{form.include_sr_browse}}</td></tr>
	    <tr><td colspan=2>Surface Reflectance NDVI</td><td colspan=2>{{form.include_sr_ndvi}}</td></tr>
            <tr style="{{optionstyle}}"><td colspan=2>Surface Reflectance NDMI</td><td colspan=2>{{form.include_sr_ndmi}}</td></tr>
            <tr style="{{optionstyle}}"><td colspan=2>Surface Reflectance NBR</td><td colspan=2>{{form.include_sr_nbr}}</td></tr>
            <tr style="{{optionstyle}}"><td colspan=2>Surface Reflectance NBR2</td><td colspan=2>{{form.include_sr_nbr2}}</td></tr>
            <tr style="{{optionstyle}}"><td colspan=2>Surface Reflectance SAVI</td><td colspan=2>{{form.include_sr_savi}}</td></tr>
            <tr style="{{optionstyle}}"><td colspan=2>Surface Reflectance EVI</td><td colspan=2>{{form.include_sr_evi}}</td></tr>         
            <tr style="{{optionstyle}}"><td colspan=2>CFMask</td><td colspan=2>{{form.include_cfmask}}</td></tr>
	    <tr style="{{optionstyle}}"><td colspan=2>Solr Index</td><td colspan=2>{{form.include_solr_index}}</td></tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
	    
	    <tr><td colspan=4>&nbsp;</td></tr>
	    <tr><td colspan=4><h5>Order Description (optional)</h5></td></tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
	    <tr><td colspan=4>{{form.note|escape }}</td></tr>
	    <tr><td colspan=4>&nbsp;</td></tr>
	    <tr><td><input type="submit" value="Submit" /></td></tr>
	</table>
    </div>
</div>
</form>

<div class="footer"></div>
<div class="spacer"></div>

{% endblock %}

orderservice/ordering/templates/orderdetails.html
{% extends "base.html" %}

{% block title %} ESPA - Order Details {% endblock %}

{% block header %}

Details for: {{ order.orderid }}

{% endblock %}

{% block content %}
<form action="/list/" method="post">
{% csrf_token %}
<div id="wrapper">

{% if scenes %}
<h4>Details for: {{ order.orderid }}</h4>

<div class="box">
	<div class="boxhead">
	    Status: {{order.get_status_display}}
	</div>
	<div class="boxbody">
{% for s in scenes %}
    {% if s.name %}
    <div class="boxitem">
    {{s.name}} - {{s.get_status_display}} {% if s.note and s.note != "''" %} ({{s.note}}){% endif %}

    {% if s.status == 'complete'%} - <a href="{{s.product_dload_url}}">Download</a>&nbsp;&nbsp;&nbsp;<a href="{{s.cksum_download_url}}">Checksum</a>{% endif %}
    </div>
    {% endif %}
{% endfor %}
</div>
</div>
{% else %}
<h4>No scenes found for {{order.orderid}}</h4>
{% endif %}
</div>
<div class="footer"></div>

<div class="spacer"></div>
{% endblock %}